root: YOUR_PATH
size: 960
download: true
batch_size: 16
tokenizer: BPE
vocab_path: pretrained\BPEvocab512_960.pkl
splits_path: pretrained\BPEsplits512_960.pkl
merges_path: pretrained\BPEmerges512_960.pkl
pad_idx: 0
unk_idx: 1
bos_idx: 2
eos_idx: 3
sample_rate: 16000
n_fft: 512
win_length: 400
hop_length: 160
n_mels: 80
n_time_masks: 10
time_mask_param: 10
n_freq_masks: 1
freq_mask_param: 27
lr: noam
base_lr: 1
d_model: 144
warmup_steps: 20000
model: ConformerAED
input_dim: 80
time_reduction_stride: 4
conformer_input_dim: 144
conformer_output_dim: 256
conformer_ffn_dim: 512
conformer_num_layers: 16
conformer_num_heads: 4
conformer_kernel_size: 31
decoder_input_dim: 256
decoder_ffn_dim: 512
decoder_num_layers: 4
decoder_num_heads: 4
seed: 42
ckpt_dir: YOUR_PATH
device: cuda:0
max_epochs: 50
gradient_clip_val: 1